import { PrismaClient } from "@prisma/client";


const prisma = new PrismaClient();

async function main() {
  // Clear existing meals
  await prisma.meal.deleteMany({});


  console.log("Cleared existing meals");

  // Create new meals with updated schema
  await prisma.meal.createMany({
    data: [
      {
        name: "Grilled Chicken Salad",
        description: "A healthy mix of grilled chicken, fresh greens, and vinaigrette dressing.",
        price: 8.99,
        category: "Salad",
        isVegan: false,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: true,
        isOrganic: false,
        calories: 350,
        protein: 40,
        carbs: 15,
        fat: 10,
        fiber: 5,
        sugar: 3,
        sodium: 320,
        vitaminA: 2500,
        vitaminC: 30,
        calcium: 120,
        iron: 2,
        allergens: ["None"]
      },
      {
        name: "Vegan Buddha Bowl",
        description: "A balanced bowl with quinoa, chickpeas, avocado, and tahini dressing.",
        price: 10.99,
        category: "Vegan",
        isVegan: true,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: true,
        calories: 500,
        protein: 20,
        carbs: 55,
        fat: 15,
        fiber: 12,
        sugar: 6,
        sodium: 240,
        vitaminA: 4000,
        vitaminC: 45,
        calcium: 150,
        iron: 6,
        allergens: ["Sesame"]
      },
      {
        name: "Classic Cheeseburger",
        description: "Juicy beef patty with cheddar cheese, lettuce, tomato, and pickles.",
        price: 9.99,
        category: "Fast Food",
        isVegan: false,
        isGlutenFree: false,
        isSugarFree: false,
        isLowFat: false,
        isOrganic: false,
        calories: 700,
        protein: 45,
        carbs: 50,
        fat: 40,
        fiber: 3,
        sugar: 8,
        sodium: 980,
        vitaminA: 600,
        vitaminC: 10,
        calcium: 300,
        iron: 4,
        allergens: ["Gluten", "Dairy"]
      },
      {
        name: "Whole Grain Breakfast Bowl",
        description: "Nutritious bowl with oats, fresh fruits, nuts and honey.",
        price: 7.99,
        category: "Breakfast",
        isVegan: false,
        isGlutenFree: false,
        isSugarFree: false,
        isLowFat: true,
        isOrganic: true,
        calories: 450,
        protein: 15,
        carbs: 75,
        fat: 12,
        fiber: 8,
        sugar: 22,
        sodium: 120,
        vitaminA: 800,
        vitaminC: 20,
        calcium: 200,
        iron: 3,
        allergens: ["Nuts", "Gluten"]
      },
      {
        name: "Tofu Stir-Fry",
        description: "Stir-fried tofu with vegetables and soy-ginger sauce.",
        price: 9.49,
        category: "Asian",
        isVegan: true,
        isGlutenFree: false,
        isSugarFree: false,
        isLowFat: true,
        isOrganic: false,
        calories: 400,
        protein: 30,
        carbs: 45,
        fat: 12,
        fiber: 6,
        sugar: 10,
        sodium: 750,
        vitaminA: 3000,
        vitaminC: 40,
        calcium: 250,
        iron: 8,
        allergens: ["Soy", "Gluten"]
      },
      {
        name: "Wild Salmon Fillet",
        description: "Grilled wild-caught salmon with roasted vegetables and herbed quinoa.",
        price: 16.99,
        category: "Seafood",
        isVegan: false,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: false,
        calories: 520,
        protein: 42,
        carbs: 25,
        fat: 28,
        fiber: 5,
        sugar: 3,
        sodium: 340,
        vitaminA: 900,
        vitaminC: 25,
        calcium: 180,
        iron: 3,
        allergens: ["Fish"]
      },
      {
        name: "Mediterranean Wrap",
        description: "Whole grain wrap filled with hummus, falafel, fresh vegetables and tzatziki.",
        price: 8.49,
        category: "Sandwich",
        isVegan: false, // Contains tzatziki
        isGlutenFree: false,
        isSugarFree: true,
        isLowFat: true,
        isOrganic: true,
        calories: 480,
        protein: 18,
        carbs: 60,
        fat: 20,
        fiber: 9,
        sugar: 5,
        sodium: 600,
        vitaminA: 1500,
        vitaminC: 35,
        calcium: 150,
        iron: 4,
        allergens: ["Gluten", "Sesame"]
      },
      {
        name: "Vegetable Curry",
        description: "A spicy blend of vegetables simmered in a rich curry sauce.",
        price: 9.99,
        category: "Indian",
        isVegan: true,
        isGlutenFree: true,
        isSugarFree: false,
        isLowFat: true,
        isOrganic: false,
        calories: 450,
        protein: 10,
        carbs: 60,
        fat: 18,
        fiber: 8,
        sugar: 7,
        sodium: 680,
        vitaminA: 4500,
        vitaminC: 38,
        calcium: 120,
        iron: 5,
        allergens: ["None"]
      },
      {
        name: "Shrimp Scampi",
        description: "Succulent shrimp sautéed in garlic butter sauce, served over pasta.",
        price: 13.99,
        category: "Seafood",
        isVegan: false,
        isGlutenFree: false,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: false,
        calories: 650,
        protein: 35,
        carbs: 70,
        fat: 25,
        fiber: 3,
        sugar: 4,
        sodium: 890,
        vitaminA: 600,
        vitaminC: 12,
        calcium: 100,
        iron: 3,
        allergens: ["Shellfish", "Gluten", "Dairy"]
      },
      {
        name: "Quinoa Power Bowl",
        description: "Protein-rich quinoa with roasted vegetables, avocado, and tahini dressing.",
        price: 11.99,
        category: "Vegan",
        isVegan: true,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: true,
        isOrganic: true,
        calories: 480,
        protein: 18,
        carbs: 65,
        fat: 16,
        fiber: 10,
        sugar: 5,
        sodium: 320,
        vitaminA: 3800,
        vitaminC: 40,
        calcium: 160,
        iron: 6,
        allergens: ["Sesame"]
      },
      {
        name: "Keto Plate",
        description: "High-fat, low-carb meal with grilled steak, avocado, and greens.",
        price: 14.99,
        category: "Specialty Diet",
        isVegan: false,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: false,
        calories: 650,
        protein: 40,
        carbs: 8,
        fat: 52,
        fiber: 5,
        sugar: 2,
        sodium: 580,
        vitaminA: 1500,
        vitaminC: 15,
        calcium: 120,
        iron: 5,
        allergens: ["None"]
      },
      {
        name: "Berry Smoothie Bowl",
        description: "Blend of mixed berries, banana, and almond milk topped with granola and seeds.",
        price: 8.49,
        category: "Breakfast",
        isVegan: true,
        isGlutenFree: false,
        isSugarFree: false,
        isLowFat: true,
        isOrganic: true,
        calories: 380,
        protein: 10,
        carbs: 65,
        fat: 8,
        fiber: 9,
        sugar: 35,
        sodium: 90,
        vitaminA: 800,
        vitaminC: 60,
        calcium: 180,
        iron: 3,
        allergens: ["Nuts", "Gluten"]
      },
      {
        name: "Chicken Tikka Masala",
        description: "Tender chicken in a creamy, spiced tomato sauce with basmati rice.",
        price: 12.99,
        category: "Indian",
        isVegan: false,
        isGlutenFree: true,
        isSugarFree: false,
        isLowFat: false,
        isOrganic: false,
        calories: 620,
        protein: 38,
        carbs: 50,
        fat: 32,
        fiber: 4,
        sugar: 8,
        sodium: 850,
        vitaminA: 1200,
        vitaminC: 20,
        calcium: 150,
        iron: 4,
        allergens: ["Dairy"]
      },
      {
        name: "Avocado Toast",
        description: "Multigrain toast topped with smashed avocado, cherry tomatoes, and microgreens.",
        price: 7.99,
        category: "Breakfast",
        isVegan: true,
        isGlutenFree: false,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: true,
        calories: 320,
        protein: 8,
        carbs: 35,
        fat: 18,
        fiber: 8,
        sugar: 3,
        sodium: 380,
        vitaminA: 1000,
        vitaminC: 15,
        calcium: 60,
        iron: 2,
        allergens: ["Gluten"]
      },
      {
        name: "Beef Teriyaki Bowl",
        description: "Tender slices of beef in teriyaki sauce with steamed rice and vegetables.",
        price: 11.99,
        category: "Asian",
        isVegan: false,
        isGlutenFree: false,
        isSugarFree: false,
        isLowFat: false,
        isOrganic: false,
        calories: 580,
        protein: 35,
        carbs: 70,
        fat: 18,
        fiber: 4,
        sugar: 18,
        sodium: 950,
        vitaminA: 900,
        vitaminC: 25,
        calcium: 80,
        iron: 4,
        allergens: ["Soy", "Gluten"]
      },
      {
        name: "Spinach and Feta Omelette",
        description: "Fluffy three-egg omelette with spinach, feta cheese, and herbs.",
        price: 8.99,
        category: "Breakfast",
        isVegan: false,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: false,
        isOrganic: false,
        calories: 380,
        protein: 25,
        carbs: 5,
        fat: 28,
        fiber: 2,
        sugar: 1,
        sodium: 620,
        vitaminA: 3500,
        vitaminC: 10,
        calcium: 320,
        iron: 4,
        allergens: ["Eggs", "Dairy"]
      },
      {
        name: "Sweet Potato Fries",
        description: "Crispy baked sweet potato fries with chipotle aioli.",
        price: 4.99,
        category: "Side",
        isVegan: false, // Aioli contains eggs
        isGlutenFree: true,
        isSugarFree: false,
        isLowFat: false,
        isOrganic: true,
        calories: 320,
        protein: 3,
        carbs: 40,
        fat: 18,
        fiber: 6,
        sugar: 8,
        sodium: 380,
        vitaminA: 12000,
        vitaminC: 30,
        calcium: 40,
        iron: 1,
        allergens: ["Eggs"]
      },
      {
        name: "Fresh Fruit Platter",
        description: "Assortment of seasonal fruits beautifully arranged.",
        price: 7.49,
        category: "Side",
        isVegan: true,
        isGlutenFree: true,
        isSugarFree: false,
        isLowFat: true,
        isOrganic: true,
        calories: 150,
        protein: 2,
        carbs: 38,
        fat: 0,
        fiber: 6,
        sugar: 30,
        sodium: 5,
        vitaminA: 1500,
        vitaminC: 90,
        calcium: 40,
        iron: 1,
        allergens: ["None"]
      },
      {
        name: "Steamed Brown Rice",
        description: "Perfectly cooked whole grain brown rice.",
        price: 3.49,
        category: "Side",
        isVegan: true,
        isGlutenFree: true,
        isSugarFree: true,
        isLowFat: true,
        isOrganic: true,
        calories: 220,
        protein: 5,
        carbs: 45,
        fat: 2,
        fiber: 3,
        sugar: 0,
        sodium: 10,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 20,
        iron: 1,
        allergens: ["None"]
      }
    ],
  });

  console.log("New meals seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
